///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyBiz_Monitoring_Phase_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyBiz_Monitoring_Phase_1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f0cbb8b4-bdf1-408c-8d1c-8a5e833f8702")]
    public partial class MyBiz_Monitoring_Phase_1Repository : RepoGenBaseFolder
    {
        static MyBiz_Monitoring_Phase_1Repository instance = new MyBiz_Monitoring_Phase_1Repository();
        MyBiz_Monitoring_Phase_1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyBiz_Monitoring_Phase_1RepositoryFolders.MagentaMyBusinessStationAppFolder _magentamybusinessstation;

        /// <summary>
        /// Gets the singleton class instance representing the MyBiz_Monitoring_Phase_1Repository element repository.
        /// </summary>
        [RepositoryFolder("f0cbb8b4-bdf1-408c-8d1c-8a5e833f8702")]
        public static MyBiz_Monitoring_Phase_1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyBiz_Monitoring_Phase_1Repository() 
            : base("MyBiz_Monitoring_Phase_1Repository", "/", null, 0, false, "f0cbb8b4-bdf1-408c-8d1c-8a5e833f8702", ".\\RepositoryImages\\MyBiz_Monitoring_Phase_1Repositoryf0cbb8b4.rximgres")
        {
            _applicationundertest = new MyBiz_Monitoring_Phase_1RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _magentamybusinessstation = new MyBiz_Monitoring_Phase_1RepositoryFolders.MagentaMyBusinessStationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f0cbb8b4-bdf1-408c-8d1c-8a5e833f8702")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b51efdab-fdae-4793-8806-e849fafc4b99")]
        public virtual MyBiz_Monitoring_Phase_1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The MagentaMyBusinessStation folder.
        /// </summary>
        [RepositoryFolder("c3d76017-8f3b-4d07-a91d-3d782d0ccce9")]
        public virtual MyBiz_Monitoring_Phase_1RepositoryFolders.MagentaMyBusinessStationAppFolder MagentaMyBusinessStation
        {
            get { return _magentamybusinessstation; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyBiz_Monitoring_Phase_1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b51efdab-fdae-4793-8806-e849fafc4b99")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyBiz_Monitoring_Phase_1RepositoryFolders.ContentFolder _content;
            MyBiz_Monitoring_Phase_1RepositoryFolders.PCol12Folder _pcol12;
            RepoItemInfo _abmeldenInfo;
            RepoItemInfo _erneuterloginInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='mybiz.magenta.at']", parentFolder, 30000, null, false, "b51efdab-fdae-4793-8806-e849fafc4b99", "")
            {
                _content = new MyBiz_Monitoring_Phase_1RepositoryFolders.ContentFolder(this);
                _pcol12 = new MyBiz_Monitoring_Phase_1RepositoryFolders.PCol12Folder(this);
                _abmeldenInfo = new RepoItemInfo(this, "ABMELDEN", ".//div[#'page-content-container']/?/?/ul/?/?/a[@innertext='ABMELDEN']", 30000, null, "77d646d7-e19d-4aa5-a1c5-3ecc964e9c86");
                _erneuterloginInfo = new RepoItemInfo(this, "ErneuterLogin", ".//div[#'help_buttons']/a[@innertext='Erneuter Login']", 30000, null, "49551ed2-12ca-488f-9b26-35f8af20df38");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b51efdab-fdae-4793-8806-e849fafc4b99")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b51efdab-fdae-4793-8806-e849fafc4b99")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ABMELDEN item.
            /// </summary>
            [RepositoryItem("77d646d7-e19d-4aa5-a1c5-3ecc964e9c86")]
            public virtual Ranorex.ATag ABMELDEN
            {
                get
                {
                    return _abmeldenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ABMELDEN item info.
            /// </summary>
            [RepositoryItemInfo("77d646d7-e19d-4aa5-a1c5-3ecc964e9c86")]
            public virtual RepoItemInfo ABMELDENInfo
            {
                get
                {
                    return _abmeldenInfo;
                }
            }

            /// <summary>
            /// The ErneuterLogin item.
            /// </summary>
            [RepositoryItem("49551ed2-12ca-488f-9b26-35f8af20df38")]
            public virtual Ranorex.ATag ErneuterLogin
            {
                get
                {
                    return _erneuterloginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ErneuterLogin item info.
            /// </summary>
            [RepositoryItemInfo("49551ed2-12ca-488f-9b26-35f8af20df38")]
            public virtual RepoItemInfo ErneuterLoginInfo
            {
                get
                {
                    return _erneuterloginInfo;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("24dbe4f0-b1fc-4ac3-8c79-80797781e5d7")]
            public virtual MyBiz_Monitoring_Phase_1RepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }

            /// <summary>
            /// The PCol12 folder.
            /// </summary>
            [RepositoryFolder("ecc2023e-cd27-4c5a-9fc9-2c252dff1ff3")]
            public virtual MyBiz_Monitoring_Phase_1RepositoryFolders.PCol12Folder PCol12
            {
                get { return _pcol12; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("24dbe4f0-b1fc-4ac3-8c79-80797781e5d7")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rufnummernplanInfo;
            RepoItemInfo _breaktextincolumndivtextincolumnngstaInfo;
            RepoItemInfo _spantag436763684123Info;
            RepoItemInfo _bizinclusivevpn500Info;
            RepoItemInfo _markusInfo;
            RepoItemInfo _tmobilegmbh16530testautomatisierunInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", ".//iframe[#'frmMain']/?/?/div", parentFolder, 30000, null, false, "24dbe4f0-b1fc-4ac3-8c79-80797781e5d7", "")
            {
                _rufnummernplanInfo = new RepoItemInfo(this, "Rufnummernplan", "?/?/tag[@tagname='app-overview']/div[1]/h1[@innertext='Rufnummernplan']", 30000, null, "b99bcd2b-23e3-4d84-ae96-7c66d647fae9");
                _breaktextincolumndivtextincolumnngstaInfo = new RepoItemInfo(this, "BreakTextInColumnDivTextInColumnNgSta", "?/?/tag[@tagname='app-overview']/div[5]/div//tag[@tagname='p-table']/div/div[1]/div/div[2]/table/tbody/?/?/td[@title='Markus']/div", 30000, null, "84548995-fe2a-4858-8155-fdb72fc5de76");
                _spantag436763684123Info = new RepoItemInfo(this, "SpanTag436763684123", "?/?/tag[@tagname='app-overview']/div[5]/div/div[1]/div/div[2]/tag[@tagname='p-table']/div/div[1]/div/div[2]/table/tbody/?/?/td[@title='43676 3684123']/?/?/span[@innertext='43676 3684123']", 30000, null, "837de131-a0c2-445e-9a84-17370a516d36");
                _bizinclusivevpn500Info = new RepoItemInfo(this, "BIZInclusiveVPN500", "?/?/tag[@tagname='app-overview']/div[5]/div/div[1]/div/div[2]/tag[@tagname='p-table']/div/div[1]/div/div[2]/table/tbody/?/?/td[@title='BIZ Inclusive VPN 500']/?/?/div[@innertext='BIZ Inclusive VPN 500']", 30000, null, "f7a82346-508b-4156-9754-455e173483ad");
                _markusInfo = new RepoItemInfo(this, "Markus", "?/?/tag[@tagname='app-overview']/div[5]/div/div[1]/div/div[2]/tag[@tagname='p-table']/div/div[1]/div/div[2]/table/tbody/?/?/td[@title='Markus']/?/?/span[@innertext='Markus']", 30000, null, "8e30d09b-f2be-423a-b44c-46fa9afaae87");
                _tmobilegmbh16530testautomatisierunInfo = new RepoItemInfo(this, "TMobileGmbH16530Testautomatisierun", "?/?/tag[@tagname='app-overview']/div[5]/div/div[1]/div/div[2]/tag[@tagname='p-table']/div/div[1]/div/div[2]/table/tbody/tr/td[7]/?/?/div[@innertext>'T-Mobile GmbH (16530) Testautomatisierung']", 30000, null, "17f3d2a2-2c67-4980-97e3-b2a027eee15b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("24dbe4f0-b1fc-4ac3-8c79-80797781e5d7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("24dbe4f0-b1fc-4ac3-8c79-80797781e5d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Rufnummernplan item.
            /// </summary>
            [RepositoryItem("b99bcd2b-23e3-4d84-ae96-7c66d647fae9")]
            public virtual Ranorex.H1Tag Rufnummernplan
            {
                get
                {
                    return _rufnummernplanInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Rufnummernplan item info.
            /// </summary>
            [RepositoryItemInfo("b99bcd2b-23e3-4d84-ae96-7c66d647fae9")]
            public virtual RepoItemInfo RufnummernplanInfo
            {
                get
                {
                    return _rufnummernplanInfo;
                }
            }

            /// <summary>
            /// The BreakTextInColumnDivTextInColumnNgSta item.
            /// </summary>
            [RepositoryItem("84548995-fe2a-4858-8155-fdb72fc5de76")]
            public virtual Ranorex.DivTag BreakTextInColumnDivTextInColumnNgSta
            {
                get
                {
                    return _breaktextincolumndivtextincolumnngstaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BreakTextInColumnDivTextInColumnNgSta item info.
            /// </summary>
            [RepositoryItemInfo("84548995-fe2a-4858-8155-fdb72fc5de76")]
            public virtual RepoItemInfo BreakTextInColumnDivTextInColumnNgStaInfo
            {
                get
                {
                    return _breaktextincolumndivtextincolumnngstaInfo;
                }
            }

            /// <summary>
            /// The SpanTag436763684123 item.
            /// </summary>
            [RepositoryItem("837de131-a0c2-445e-9a84-17370a516d36")]
            public virtual Ranorex.SpanTag SpanTag436763684123
            {
                get
                {
                    return _spantag436763684123Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag436763684123 item info.
            /// </summary>
            [RepositoryItemInfo("837de131-a0c2-445e-9a84-17370a516d36")]
            public virtual RepoItemInfo SpanTag436763684123Info
            {
                get
                {
                    return _spantag436763684123Info;
                }
            }

            /// <summary>
            /// The BIZInclusiveVPN500 item.
            /// </summary>
            [RepositoryItem("f7a82346-508b-4156-9754-455e173483ad")]
            public virtual Ranorex.DivTag BIZInclusiveVPN500
            {
                get
                {
                    return _bizinclusivevpn500Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BIZInclusiveVPN500 item info.
            /// </summary>
            [RepositoryItemInfo("f7a82346-508b-4156-9754-455e173483ad")]
            public virtual RepoItemInfo BIZInclusiveVPN500Info
            {
                get
                {
                    return _bizinclusivevpn500Info;
                }
            }

            /// <summary>
            /// The Markus item.
            /// </summary>
            [RepositoryItem("8e30d09b-f2be-423a-b44c-46fa9afaae87")]
            public virtual Ranorex.SpanTag Markus
            {
                get
                {
                    return _markusInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Markus item info.
            /// </summary>
            [RepositoryItemInfo("8e30d09b-f2be-423a-b44c-46fa9afaae87")]
            public virtual RepoItemInfo MarkusInfo
            {
                get
                {
                    return _markusInfo;
                }
            }

            /// <summary>
            /// The TMobileGmbH16530Testautomatisierun item.
            /// </summary>
            [RepositoryItem("17f3d2a2-2c67-4980-97e3-b2a027eee15b")]
            public virtual Ranorex.DivTag TMobileGmbH16530Testautomatisierun
            {
                get
                {
                    return _tmobilegmbh16530testautomatisierunInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TMobileGmbH16530Testautomatisierun item info.
            /// </summary>
            [RepositoryItemInfo("17f3d2a2-2c67-4980-97e3-b2a027eee15b")]
            public virtual RepoItemInfo TMobileGmbH16530TestautomatisierunInfo
            {
                get
                {
                    return _tmobilegmbh16530testautomatisierunInfo;
                }
            }
        }

        /// <summary>
        /// The PCol12Folder folder.
        /// </summary>
        [RepositoryFolder("ecc2023e-cd27-4c5a-9fc9-2c252dff1ff3")]
        public partial class PCol12Folder : RepoGenBaseFolder
        {
            TdTag777InfoClass _tdtag777Info;
            RepoItemInfo _ngtnsc6512uiautocompleteuiautocomInfo;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new PCol12  folder.
            /// </summary>
            public PCol12Folder(RepoGenBaseFolder parentFolder) :
                    base("PCol12", ".//iframe[#'frmMain']/body/div/?/?/tag[@tagname='app-overview']/div[5]/div/div[1]", parentFolder, 30000, null, false, "ecc2023e-cd27-4c5a-9fc9-2c252dff1ff3", "")
            {
                _tdtag777Info = new TdTag777InfoClass(this);
                _ngtnsc6512uiautocompleteuiautocomInfo = new RepoItemInfo(this, "NgTnsC6512UiAutocompleteUiAutocom", "div/div[1]/tag/div/div/div[1]//tag[@tagname='p-autocomplete']/span", 30000, null, "cd044fa0-a99c-46b1-8ed2-45dfad6603a0");
                _textInfo = new RepoItemInfo(this, "Text", "div/div[1]/tag/div/div/div[1]//ul/?/?/input[@type='text']", 30000, null, "012db9b4-073e-48c0-83a3-ce0b0c1a7802");
            }

            /// <summary>
            /// The TdTag777InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("b73f74bc-179b-4acf-be5d-012a696a022a")]
            public class TdTag777InfoClass : RepoItemInfo
            {
                /// <summary>
                /// TdTag777InfoClass class constructor.
                /// </summary>
                public TdTag777InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TdTag777", ".//tag[@tagname='p-table']/div/div[1]/div/div[2]/table//td[@title='777']", 30000, null, "b73f74bc-179b-4acf-be5d-012a696a022a")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("35e80028-974a-43f3-8293-18f4cb9f8273")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("35e80028-974a-43f3-8293-18f4cb9f8273");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("35e80028-974a-43f3-8293-18f4cb9f8273")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("35e80028-974a-43f3-8293-18f4cb9f8273", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ecc2023e-cd27-4c5a-9fc9-2c252dff1ff3")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ecc2023e-cd27-4c5a-9fc9-2c252dff1ff3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TdTag777 item.
            /// </summary>
            [RepositoryItem("b73f74bc-179b-4acf-be5d-012a696a022a")]
            public virtual Ranorex.TdTag TdTag777
            {
                get
                {
                    return _tdtag777Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTag777 item info.
            /// </summary>
            [RepositoryItemInfo("b73f74bc-179b-4acf-be5d-012a696a022a")]
            public virtual TdTag777InfoClass TdTag777Info
            {
                get
                {
                    return _tdtag777Info;
                }
            }

            /// <summary>
            /// The NgTnsC6512UiAutocompleteUiAutocom item.
            /// </summary>
            [RepositoryItem("cd044fa0-a99c-46b1-8ed2-45dfad6603a0")]
            public virtual Ranorex.SpanTag NgTnsC6512UiAutocompleteUiAutocom
            {
                get
                {
                    return _ngtnsc6512uiautocompleteuiautocomInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NgTnsC6512UiAutocompleteUiAutocom item info.
            /// </summary>
            [RepositoryItemInfo("cd044fa0-a99c-46b1-8ed2-45dfad6603a0")]
            public virtual RepoItemInfo NgTnsC6512UiAutocompleteUiAutocomInfo
            {
                get
                {
                    return _ngtnsc6512uiautocompleteuiautocomInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("012db9b4-073e-48c0-83a3-ce0b0c1a7802")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("012db9b4-073e-48c0-83a3-ce0b0c1a7802")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

        /// <summary>
        /// The MagentaMyBusinessStationAppFolder folder.
        /// </summary>
        [RepositoryFolder("c3d76017-8f3b-4d07-a91d-3d782d0ccce9")]
        public partial class MagentaMyBusinessStationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jusernameInfo;
            RepoItemInfo _jpasswordInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new MagentaMyBusinessStation  folder.
            /// </summary>
            public MagentaMyBusinessStationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MagentaMyBusinessStation", "/dom[@domain='tgate.magenta.at']", parentFolder, 30000, null, false, "c3d76017-8f3b-4d07-a91d-3d782d0ccce9", "")
            {
                _jusernameInfo = new RepoItemInfo(this, "JUsername", ".//input[#'j_username']", 30000, null, "b8e29698-a045-4d8b-b870-1651db78e3ab");
                _jpasswordInfo = new RepoItemInfo(this, "JPassword", ".//input[#'j_password']", 30000, null, "634ba03b-6ca5-44d9-82d6-3a56dc4678b6");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "d1afa893-bcde-4ad3-85ef-155f04ad38b7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3d76017-8f3b-4d07-a91d-3d782d0ccce9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3d76017-8f3b-4d07-a91d-3d782d0ccce9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JUsername item.
            /// </summary>
            [RepositoryItem("b8e29698-a045-4d8b-b870-1651db78e3ab")]
            public virtual Ranorex.InputTag JUsername
            {
                get
                {
                    return _jusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JUsername item info.
            /// </summary>
            [RepositoryItemInfo("b8e29698-a045-4d8b-b870-1651db78e3ab")]
            public virtual RepoItemInfo JUsernameInfo
            {
                get
                {
                    return _jusernameInfo;
                }
            }

            /// <summary>
            /// The JPassword item.
            /// </summary>
            [RepositoryItem("634ba03b-6ca5-44d9-82d6-3a56dc4678b6")]
            public virtual Ranorex.InputTag JPassword
            {
                get
                {
                    return _jpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JPassword item info.
            /// </summary>
            [RepositoryItemInfo("634ba03b-6ca5-44d9-82d6-3a56dc4678b6")]
            public virtual RepoItemInfo JPasswordInfo
            {
                get
                {
                    return _jpasswordInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("d1afa893-bcde-4ad3-85ef-155f04ad38b7")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("d1afa893-bcde-4ad3-85ef-155f04ad38b7")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
